# master为hexo博客所在分支
branches:
  only:
  - master
language: node_js

sudo: false

node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_7e497eed9f60_key -iv $encrypted_7e497eed9f60_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp doc/ssh_config ~/.ssh/config
- git config --global user.name "logan62334"
- git config --global user.email logan62334@gmail.com
- git clone -b master git@github.com:logan62334/logan62334.github.io.git .deploy_git

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save

script:
- hexo clean
- hexo g
- hexo d